'use strict';window.DOMHandler=class{constructor(c,d){this._iRuntime=c;this._componentId=d;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(c,d,g,k){this._iRuntime.PostToRuntimeComponent(this._componentId,c,d,g,k)}PostToRuntimeAsync(c,d,g,k){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,c,d,g,k)}_PostToRuntimeMaybeSync(c,d,g){this._iRuntime.UsesWorker()?this.PostToRuntime(c,d,g):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:c,dispatchOpts:g||null,data:d,responseId:null})}AddRuntimeMessageHandler(c,d){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,c,d)}AddRuntimeMessageHandlers(c){for(const [d,g]of c)this.AddRuntimeMessageHandler(d,g)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(c,d){this._callback=c;this._interval=d;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(c){this._canRunImmediate=!!c}Call(){if(-1===this._timerId){var c=Date.now(),d=c-this._lastCallTime,g=this._interval;d>=g&&this._canRunImmediate?(this._lastCallTime=c,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(g-d,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(c,d){super(c,d);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",g=>this._OnCreate(g)],["destroy",g=>this._OnDestroy(g)],["set-visible",g=>this._OnSetVisible(g)],["update-position",g=>this._OnUpdatePosition(g)],["update-state",g=>this._OnUpdateState(g)],["focus",g=>this._OnSetFocus(g)],["set-css-style",g=>this._OnSetCssStyle(g)],["set-attribute",g=>this._OnSetAttribute(g)],["remove-attribute",
g=>this._OnRemoveAttribute(g)]]);this.AddDOMElementMessageHandler("get-element",g=>g)}SetAutoAttach(c){this._autoAttach=!!c}AddDOMElementMessageHandler(c,d){this.AddRuntimeMessageHandler(c,g=>{const k=this._elementMap.get(g.elementId);return d(k,g)})}_OnCreate(c){const d=c.elementId,g=this.CreateElement(d,c);this._elementMap.set(d,g);c.isVisible||(g.style.display="none");c=this._GetFocusElement(g);c.addEventListener("focus",k=>this._OnFocus(d));c.addEventListener("blur",k=>this._OnBlur(d));this._autoAttach&&
document.body.appendChild(g)}CreateElement(c,d){throw Error("required override");}DestroyElement(c){}_OnDestroy(c){c=c.elementId;const d=this._elementMap.get(c);this.DestroyElement(d);this._autoAttach&&d.parentElement.removeChild(d);this._elementMap.delete(c)}PostToRuntimeElement(c,d,g){g||(g={});g.elementId=d;this.PostToRuntime(c,g)}_PostToRuntimeElementMaybeSync(c,d,g){g||(g={});g.elementId=d;this._PostToRuntimeMaybeSync(c,g)}_OnSetVisible(c){this._autoAttach&&(this._elementMap.get(c.elementId).style.display=
c.isVisible?"":"none")}_OnUpdatePosition(c){if(this._autoAttach){var d=this._elementMap.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=c.height+"px";c=c.fontSize;null!==c&&(d.style.fontSize=c+"em")}}_OnUpdateState(c){const d=this._elementMap.get(c.elementId);this.UpdateState(d,c)}UpdateState(c,d){throw Error("required override");}_GetFocusElement(c){return c}_OnFocus(c){this.PostToRuntimeElement("elem-focused",c)}_OnBlur(c){this.PostToRuntimeElement("elem-blurred",
c)}_OnSetFocus(c){const d=this._GetFocusElement(this._elementMap.get(c.elementId));c.focus?d.focus():d.blur()}_OnSetCssStyle(c){this._elementMap.get(c.elementId).style[c.prop]=c.val}_OnSetAttribute(c){this._elementMap.get(c.elementId).setAttribute(c.name,c.val)}_OnRemoveAttribute(c){this._elementMap.get(c.elementId).removeAttribute(c.name)}GetElementById(c){return this._elementMap.get(c)}};"use strict";
{const c=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let d=0;function g(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.isStringSrc?new Promise(e=>{const f="c3_resolve_"+d;++d;self[f]=e;a.textContent=b.str+`\n\nself["${f}"]();`;document.head.appendChild(a)}):new Promise((e,f)=>{a.onload=e;a.onerror=f;a.src=b;document.head.appendChild(a)})}let k=!1,l=!1;function v(){if(!k){try{new Worker("blob://",{get type(){l=!0}})}catch(b){}k=!0}return l}
let q=new Audio;const D={"audio/webm; codecs=opus":!!q.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!q.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!q.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!q.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!q.canPlayType("audio/mp4"),"audio/mpeg":!!q.canPlayType("audio/mpeg")};q=null;async function w(b){b=await E(b);return(new TextDecoder("utf-8")).decode(b)}function E(b){return new Promise((a,
e)=>{const f=new FileReader;f.onload=h=>a(h.target.result);f.onerror=h=>e(h);f.readAsArrayBuffer(b)})}const y=[];let u=0;window.RealFile=window.File;const x=[],z=new Map,A=new Map;let t=0;const B=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");B.push(b)};const C=new Set(["cordova","playable-ad","instant-games"]);function F(b){return C.has(b)}let G=!1;window.RuntimeInterface=class b{constructor(a){this._useWorker=a.useWorker;this._messageChannelPort=
null;this._baseUrl="";this._scriptFolder=a.scriptFolder;this._workerScriptURLs={};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=a.exportType;!this._useWorker||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&v()||(this._useWorker=!1);F(this._exportType)&&this._useWorker&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is currently disabled in WebViews. Reverting to DOM mode."),
this._useWorker=!1);this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",e=>this._OnCordovaFetchLocalFile(e));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",
e=>this._OnCreateJobWorker(e));"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return c&&
"cordova"===this._exportType}IsiOSWebView(){return c&&F(this._exportType)||navigator.standalone}async _Init(a){"macos-wkwebview"===this._exportType&&this._SendWrapperMessage({type:"ready"});if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let f=0,h=a.engineScripts.length;f<h;++f){var e=a.engineScripts[f].toLowerCase();this._localFileStrings.hasOwnProperty(e)?a.engineScripts[f]={isStringSrc:!0,str:this._localFileStrings[e]}:
this._localFileBlobs.hasOwnProperty(e)&&(a.engineScripts[f]=URL.createObjectURL(this._localFileBlobs[e]))}}a.baseUrl?this._baseUrl=a.baseUrl:(e=location.origin,this._baseUrl=("null"===e?"file:///":e)+location.pathname,e=this._baseUrl.lastIndexOf("/"),-1!==e&&(this._baseUrl=this._baseUrl.substr(0,e+1)));a.workerScripts&&(this._workerScriptURLs=a.workerScripts);e=new MessageChannel;this._messageChannelPort=e.port1;this._messageChannelPort.onmessage=f=>this._OnMessageFromRuntime(f.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(f=>this._OnMessageFromDebugger(f));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this._useWorker?await this._InitWorker(a,e.port2):await this._InitDOM(a,e.port2)}_GetWorkerURL(a){a=this._workerScriptURLs.hasOwnProperty(a)?this._workerScriptURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptURLs.hasOwnProperty("workermain.js")?
this._workerScriptURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a.toLowerCase())?this._localFileBlobs[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async CreateWorker(a,e,f){if(a.startsWith("blob:"))return new Worker(a,f);if(this.IsiOSCordova()&&"file:"===location.protocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(this._scriptFolder+a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),
f);a=new URL(a,e);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),f)}return new Worker(a,f)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}_GetCommonRuntimeOptions(a){return{baseUrl:this._baseUrl,windowInnerWidth:this._GetWindowInnerWidth(),windowInnerHeight:this._GetWindowInnerHeight(),devicePixelRatio:window.devicePixelRatio,
isFullscreen:b.IsDocumentFullscreen(),projectData:a.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.cr_swClientId||"",exportType:a.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),supportedAudioFormats:D,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+
"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,e){var f=this._GetWorkerURL(a.workerMainUrl);this._worker=await this.CreateWorker(f,this._baseUrl,{type:"module",name:"Runtime"});this._canvas=document.createElement("canvas");this._canvas.style.display="none";f=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);
window.c3canvas=this._canvas;this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),{type:"init-runtime",isInWorker:!0,messagePort:e,canvas:f,workerDependencyScripts:a.workerDependencyScripts||[],engineScripts:a.engineScripts,projectScripts:a.projectScripts,mainProjectScript:a.mainProjectScript,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[e,f,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=x.map(h=>new h(this));this._FindRuntimeDOMHandler();self.c3_callFunction=
(h,m)=>this._runtimeDomHandler._InvokeFunctionFromJS(h,m);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(a,e){this._canvas=document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=x.map(n=>new n(this));this._FindRuntimeDOMHandler();var f=a.engineScripts.map(n=>"string"===typeof n?(new URL(n,this._baseUrl)).toString():
n);Array.isArray(a.workerDependencyScripts)&&f.unshift(...a.workerDependencyScripts);f=await Promise.all(f.map(n=>this._MaybeGetCordovaScriptURL(n)));await Promise.all(f.map(n=>g(n)));f=self.C3_ProjectScriptsStatus;const h=a.mainProjectScript,m=a.projectScripts;for(let [n,p]of m)if(p||(p=n),n===h)try{p=await this._MaybeGetCordovaScriptURL(p),await g(p),"preview"!==this._exportType||f[n]||this._ReportProjectMainScriptError(n,"main script did not run to completion")}catch(r){this._ReportProjectMainScriptError(n,
r)}else if("scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))p=await this._MaybeGetCordovaScriptURL(p),await g(p);"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this._GetCommonRuntimeOptions(a),
{isInWorker:!1,messagePort:e,canvas:this._canvas,runOnStartupFunctions:B}),this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectMainScriptError(a,e){this._RemoveLoadingMessage();console.error(`[Preview] Failed to load project main script (${a}): `,e);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,e,f,h,m){this._messageChannelPort.postMessage({type:"event",component:a,handler:e,dispatchOpts:h||null,data:f,responseId:null},m)}PostToRuntimeComponentAsync(a,
e,f,h,m){const n=t++,p=new Promise((r,H)=>{A.set(n,{resolve:r,reject:H})});this._messageChannelPort.postMessage({type:"event",component:a,handler:e,dispatchOpts:h||null,data:f,responseId:n},m);return p}["_OnMessageFromRuntime"](a){const e=a.type;if("event"===e)return this._OnEventFromRuntime(a);if("result"===e)this._OnResultFromRuntime(a);else if("runtime-ready"===e)this._OnRuntimeReady();else if("alert-error"===e)this._RemoveLoadingMessage(),alert(a.message);else if("creating-runtime"===e)this._OnBeforeCreateRuntime();
else throw Error(`unknown message '${e}'`);}_OnEventFromRuntime(a){const e=a.component,f=a.handler,h=a.data,m=a.responseId;if(a=z.get(e))if(a=a.get(f)){var n=null;try{n=a(h)}catch(p){console.error(`Exception in '${e}' handler '${f}':`,p);null!==m&&this._PostResultToRuntime(m,!1,""+p);return}if(null===m)return n;n&&n.then?n.then(p=>this._PostResultToRuntime(m,!0,p)).catch(p=>{console.error(`Rejection from '${e}' handler '${f}':`,p);this._PostResultToRuntime(m,!1,""+p)}):this._PostResultToRuntime(m,
!0,n)}else console.warn(`[DOM] No handler '${f}' for component '${e}'`);else console.warn(`[DOM] No event handlers for component '${e}'`)}_PostResultToRuntime(a,e,f){let h;f&&f.transferables&&(h=f.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:e,result:f},h)}_OnResultFromRuntime(a){const e=a.responseId,f=a.isOk;a=a.result;const h=A.get(e);f?h.resolve(a):h.reject(a);A.delete(e)}AddRuntimeComponentMessageHandler(a,e,f){let h=z.get(a);h||(h=new Map,z.set(a,h));if(h.has(e))throw Error(`[DOM] Component '${a}' already has handler '${e}'`);
h.set(e,f)}static AddDOMHandlerClass(a){if(x.includes(a))throw Error("DOM handler already added");x.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger","message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||G)}static _SetWrapperIsFullscreenFlag(a){G=!!a}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.push(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){a=this._rafCallbacks.indexOf(a);if(-1===a)throw Error("invalid callback");this._rafCallbacks.splice(a,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&
this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!D[a]}async _WasmDecodeWebMOpus(a){a=
await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}IsAbsoluteURL(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _MaybeGetCordovaScriptURL(a){return"cordova"===this._exportType&&(a.startsWith("file:")||"file:"===location.protocol&&this.IsRelativeURL(a))?(a.startsWith(this._baseUrl)&&(a=a.substr(this._baseUrl.length)),a=await this.CordovaFetchLocalFileAsArrayBuffer(a),
a=new Blob([a],{type:"application/javascript"}),URL.createObjectURL(a)):a}async _OnCordovaFetchLocalFile(a){const e=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(e);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(e);default:throw Error("unsupported type");}}_GetPermissionAPI(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}_MapPermissionID(a,
e){a=a[e];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const e=this._GetPermissionAPI();return new Promise((f,h)=>e.checkPermission(this._MapPermissionID(e,a),m=>f(!!m.hasPermission),h))}_RequestPermission(a){const e=this._GetPermissionAPI();return new Promise((f,h)=>e.requestPermission(this._MapPermissionID(e,a),m=>f(!!m.hasPermission),h))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const e of a)if(!await this._HasPermission(e)&&
!1===await this._RequestPermission(e))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const e=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((f,h)=>{window.resolveLocalFileSystemURL(e,m=>{m.file(f,h)},h)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await w(a)}_CordovaMaybeStartNextArrayBufferRead(){if(y.length&&!(8<=u)){u++;
var a=y.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((e,f)=>{y.push({filename:a,successCallback:h=>{u--;this._CordovaMaybeStartNextArrayBufferRead();e(h)},errorCallback:h=>{u--;this._CordovaMaybeStartNextArrayBufferRead();f(h)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,e,f){try{const h=await this.CordovaFetchLocalFile(a),m=await E(h);
e(m)}catch(h){f(h)}}_SendWrapperMessage(a){if("windows-webview2"===this._exportType)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this._exportType)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async _ConvertDataUrisToBlobs(){const a=[];for(const [e,f]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(e,f));await Promise.all(a)}async _ConvertDataUriToBlobs(a,e){if("object"===
typeof e)this._localFileBlobs[a]=new Blob([e.str],{type:e.type}),this._localFileStrings[a]=e.str;else{let f=await this._FetchDataUri(e);f||(f=this._DataURIToBinaryBlobSync(e));this._localFileBlobs[a]=f}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(e){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",e),null}}_DataURIToBinaryBlobSync(a){a=
this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var e=a.indexOf(",");if(0>e)throw new URIError("expected comma in data: uri");var f=a.substring(5,e);a=a.substring(e+1);e=f.split(";");f=e[0]||"";const h=e[2];a="base64"===e[1]||"base64"===h?atob(a):decodeURIComponent(a);return{mime_type:f,data:a}}_BinaryStringToBlob(a,e){var f=a.length;let h=f>>2,m=new Uint8Array(f),n=new Uint32Array(m.buffer,0,h),p,r;for(r=p=0;p<h;++p)n[p]=a.charCodeAt(r++)|a.charCodeAt(r++)<<
8|a.charCodeAt(r++)<<16|a.charCodeAt(r++)<<24;for(f&=3;f--;)m[r]=a.charCodeAt(r),++r;return new Blob([m],{type:e})}}}"use strict";
{const c=self.RuntimeInterface;function d(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const g=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),k={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},l={dispatchUserScriptEvent:!0},v={dispatchRuntimeEvent:!0};function q(b){return new Promise((a,e)=>{const f=document.createElement("link");f.onload=()=>a(f);f.onerror=
h=>e(h);f.rel="stylesheet";f.href=b;document.head.appendChild(f)})}function D(b){return new Promise((a,e)=>{const f=new Image;f.onload=()=>a(f);f.onerror=h=>e(h);f.src=b})}async function w(b){b=URL.createObjectURL(b);try{return await D(b)}finally{URL.revokeObjectURL(b)}}function E(b){return new Promise((a,e)=>{let f=new FileReader;f.onload=h=>a(h.target.result);f.onerror=h=>e(h);f.readAsText(b)})}async function y(b,a,e){if(!/firefox/i.test(navigator.userAgent))return await w(b);var f=await E(b);f=
(new DOMParser).parseFromString(f,"image/svg+xml");const h=f.documentElement;if(h.hasAttribute("width")&&h.hasAttribute("height")){const m=h.getAttribute("width"),n=h.getAttribute("height");if(!m.includes("%")&&!n.includes("%"))return await w(b)}h.setAttribute("width",a+"px");h.setAttribute("height",e+"px");f=(new XMLSerializer).serializeToString(f);b=new Blob([f],{type:"image/svg+xml"});return await w(b)}function u(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);
return!1}const x=new Set(["input","textarea","datalist","select"]);function z(b){return x.has(b.tagName.toLowerCase())||u(b)}const A=new Set(["canvas","body","html"]);function t(b){const a=b.target.tagName.toLowerCase();A.has(a)&&b.preventDefault()}function B(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await w(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";
document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]}};self.C3_RasterSvgImageBlob=async function(b,a,e,f,h){b=await y(b,a,e);const m=document.createElement("canvas");m.width=f;m.height=h;m.getContext("2d").drawImage(b,0,0,a,e);return m};let C=!1;document.addEventListener("pause",()=>C=!0);document.addEventListener("resume",()=>C=!1);function F(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}function G(){const b=
document.activeElement;if(!b)return!1;const a=b.tagName.toLowerCase(),e=new Set("email number password search tel text url".split(" "));return"textarea"===a?!0:"input"===a?e.has(b.type.toLowerCase()||"text"):u(b)}c.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=
this._debugHighlightElem=null;b.AddRuntimeComponentMessageHandler("canvas","update-size",f=>this._OnUpdateCanvasSize(f));b.AddRuntimeComponentMessageHandler("runtime","invoke-download",f=>this._OnInvokeDownload(f));b.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",f=>this._OnRasterSvgImage(f));b.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",f=>this._OnGetSvgImageSize(f));b.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",f=>this._OnSetTargetOrientation(f));
b.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());b.AddRuntimeComponentMessageHandler("runtime","post-to-debugger",f=>this._OnPostToDebugger(f));b.AddRuntimeComponentMessageHandler("runtime","go-to-script",f=>this._OnPostToDebugger(f));b.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());b.AddRuntimeComponentMessageHandler("runtime","debug-highlight",f=>this._OnDebugHighlight(f));b.AddRuntimeComponentMessageHandler("runtime",
"enable-device-orientation",()=>this._AttachDeviceOrientationEvent());b.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",()=>this._AttachDeviceMotionEvent());b.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",f=>this._OnAddStylesheet(f));b.AddRuntimeComponentMessageHandler("runtime","alert",f=>this._OnAlert(f));b.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",
f=>{const h=f.target,m=h.tagName.toLowerCase();a.has(m)||u(h)||f.preventDefault()});const e=b.GetCanvas();window.addEventListener("selectstart",t);window.addEventListener("gesturehold",t);e.addEventListener("selectstart",t);e.addEventListener("gesturehold",t);window.addEventListener("touchstart",t,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",t,{passive:!1}),e.addEventListener("pointerdown",t)):e.addEventListener("touchstart",t);this._mousePointerLastButtons=
0;window.addEventListener("mousedown",f=>{1===f.button&&f.preventDefault()});window.addEventListener("mousewheel",B,{passive:!1});window.addEventListener("wheel",B,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",
f=>this._OnFullscreenError(f));window.addEventListener("webkitfullscreenerror",f=>this._OnFullscreenError(f));window.addEventListener("mozfullscreenerror",f=>this._OnFullscreenError(f));b.IsiOSWebView()&&window.addEventListener("focusout",()=>{G()||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=f=>this._OnWrapperMessage(f);this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?
(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",()=>this._OnVisibilityChange(document.hidden));return{isSuspended:!(!document.hidden&&!C)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:F()});this._mousePointerLastButtons=0});window.addEventListener("focusin",
a=>{z(a.target)&&this._PostRuntimeEvent("keyboard-blur")});window.addEventListener("keydown",a=>this._OnKeyEvent("keydown",a));window.addEventListener("keyup",a=>this._OnKeyEvent("keyup",a));window.addEventListener("dblclick",a=>this._OnMouseEvent("dblclick",a,k));window.addEventListener("wheel",a=>this._OnMouseWheelEvent("wheel",a));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{this._HandlePointerDownFocus(a);this._OnPointerEvent("pointerdown",a)}),this._iRuntime.UsesWorker()&&
"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",a=>this._OnPointerRawUpdate(a))):window.addEventListener("pointermove",a=>this._OnPointerEvent("pointermove",a)),window.addEventListener("pointerup",a=>this._OnPointerEvent("pointerup",a)),window.addEventListener("pointercancel",a=>this._OnPointerEvent("pointercancel",
a))):(window.addEventListener("mousedown",a=>{this._HandlePointerDownFocus(a);this._OnMouseEventAsPointer("pointerdown",a)}),window.addEventListener("mousemove",a=>this._OnMouseEventAsPointer("pointermove",a)),window.addEventListener("mouseup",a=>this._OnMouseEventAsPointer("pointerup",a)),window.addEventListener("touchstart",a=>{this._HandlePointerDownFocus(a);this._OnTouchEvent("pointerdown",a)}),window.addEventListener("touchmove",a=>this._OnTouchEvent("pointermove",a)),window.addEventListener("touchend",
a=>this._OnTouchEvent("pointerup",a)),window.addEventListener("touchcancel",a=>this._OnTouchEvent("pointercancel",a)));const b=()=>this._PlayPendingMedia();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}_PostRuntimeEvent(b,a){this.PostToRuntime(b,a||null,v)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){const b=
this._GetWindowInnerWidth(),a=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:b,innerHeight:a,devicePixelRatio:window.devicePixelRatio,isFullscreen:c.IsDocumentFullscreen()});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(b,a,0))}_ScheduleSimulatedResize(b,a,e){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>
this._OnSimulatedResize(b,a,e),48)}_OnSimulatedResize(b,a,e){const f=this._GetWindowInnerWidth(),h=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;f!=b||h!=a?this._PostRuntimeEvent("window-resize",{innerWidth:f,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:c.IsDocumentFullscreen()}):10>e&&this._ScheduleSimulatedResize(f,h,e+1)}_OnSetTargetOrientation(b){this._targetOrientation=b.targetOrientation}_TrySetTargetOrientation(){const b=this._targetOrientation;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",a)}}_OnFullscreenChange(){const b=
c.IsDocumentFullscreen();b&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:b,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(b){console.warn("[Construct 3] Fullscreen request failed: ",b);this.PostToRuntime("fullscreenerror",{isFullscreen:c.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(b){b?this._iRuntime._CancelAnimationFrame():
this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:b})}_OnKeyEvent(b,a){"Backspace"===a.key&&t(a);const e=g.get(a.code)||a.code;this._PostToRuntimeMaybeSync(b,{code:e,key:a.key,which:a.which,repeat:a.repeat,altKey:a.altKey,ctrlKey:a.ctrlKey,metaKey:a.metaKey,shiftKey:a.shiftKey,timeStamp:a.timeStamp},k)}_OnMouseWheelEvent(b,a){this.PostToRuntime(b,{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,
timeStamp:a.timeStamp},k)}_OnMouseEvent(b,a,e){d(a)||this._PostToRuntimeMaybeSync(b,{button:a.button,buttons:a.buttons,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,timeStamp:a.timeStamp},e)}_OnMouseEventAsPointer(b,a){if(!d(a)){var e=this._mousePointerLastButtons;"pointerdown"===b&&0!==e?b="pointermove":"pointerup"===b&&0!==a.buttons&&(b="pointermove");this._PostToRuntimeMaybeSync(b,{pointerId:1,pointerType:"mouse",button:a.button,buttons:a.buttons,lastButtons:e,clientX:a.clientX,
clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:a.timeStamp},k);this._mousePointerLastButtons=a.buttons;this._OnMouseEvent(a.type,a,l)}}_OnPointerEvent(b,a){this._pointerRawUpdateRateLimiter&&"pointermove"!==b&&this._pointerRawUpdateRateLimiter.Reset();var e=0;"mouse"===a.pointerType&&(e=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(b,{pointerId:a.pointerId,pointerType:a.pointerType,button:a.button,buttons:a.buttons,
lastButtons:e,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:a.width||0,height:a.height||0,pressure:a.pressure||0,tangentialPressure:a.tangentialPressure||0,tiltX:a.tiltX||0,tiltY:a.tiltY||0,twist:a.twist||0,timeStamp:a.timeStamp},k);"mouse"===a.pointerType&&(e="mousemove","pointerdown"===b?e="mousedown":"pointerup"===b&&(e="mouseup"),this._OnMouseEvent(e,a,l),this._mousePointerLastButtons=a.buttons)}_OnPointerRawUpdate(b){this._lastPointerRawUpdateEvent=b;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",
this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(b,a){for(let e=0,f=a.changedTouches.length;e<f;++e){const h=a.changedTouches[e];this._PostToRuntimeMaybeSync(b,{pointerId:h.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:2*(h.radiusX||h.webkitRadiusX||0),height:2*(h.radiusY||h.webkitRadiusY||0),pressure:h.force||h.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:h.rotationAngle||
0,timeStamp:a.timeStamp},k)}}_HandlePointerDownFocus(b){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(b.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&document.activeElement.blur()}_IsElementCanvasOrDocument(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",
b=>this._OnDeviceOrientation(b)),window.addEventListener("deviceorientationabsolute",b=>this._OnDeviceOrientationAbsolute(b)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=!0,window.addEventListener("devicemotion",b=>this._OnDeviceMotion(b)))}_OnDeviceOrientation(b){this.PostToRuntime("deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},
k)}_OnDeviceOrientationAbsolute(b){this.PostToRuntime("deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},k)}_OnDeviceMotion(b){let a=null;var e=b.acceleration;e&&(a={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=b.accelerationIncludingGravity;f&&(e={x:f.x||0,y:f.y||0,z:f.z||0});f=null;const h=b.rotationRate;h&&(f={alpha:h.alpha||0,beta:h.beta||0,gamma:h.gamma||0});this.PostToRuntime("devicemotion",{acceleration:a,accelerationIncludingGravity:e,
rotationRate:f,interval:b.interval,timeStamp:b.timeStamp},k)}_OnUpdateCanvasSize(b){const a=this.GetRuntimeInterface().GetCanvas();a.style.width=b.styleWidth+"px";a.style.height=b.styleHeight+"px";a.style.marginLeft=b.marginLeft+"px";a.style.marginTop=b.marginTop+"px";this._isFirstSizeUpdate&&(a.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(b){const a=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=b;e.href=a;e.download=b;f.appendChild(e);e.click();
f.removeChild(e)}async _OnRasterSvgImage(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async _OnGetSvgImageSize(b){return await self.C3_GetSvgImageSize(b.blob)}async _OnAddStylesheet(b){await q(b.url)}_PlayPendingMedia(){var b=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const a of b)(b=
a.play())&&b.catch(e=>{this._mediaRemovedPendingPlay.has(a)||this._mediaPendingPlay.add(a)})}TryPlayMedia(b){if("function"!==typeof b.play)throw Error("missing play function");this._mediaRemovedPendingPlay.delete(b);let a;try{a=b.play()}catch(e){this._mediaPendingPlay.add(b);return}a&&a.catch(e=>{this._mediaRemovedPendingPlay.has(b)||this._mediaPendingPlay.add(b)})}RemovePendingPlay(b){this._mediaPendingPlay.delete(b);this._mediaRemovedPendingPlay.add(b)}SetSilent(b){this._isSilent=!!b}_OnHideCordovaSplash(){navigator.splashscreen&&
navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(b){if(b.show){this._debugHighlightElem||(this._debugHighlightElem=document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var a=this._debugHighlightElem;a.style.display="";a.style.left=b.left-1+"px";a.style.top=b.top-1+"px";a.style.width=b.width+2+"px";a.style.height=b.height+2+"px";a.textContent=b.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display=
"none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}_InvokeFunctionFromJS(b,a){return this.PostToRuntimeAsync("js-invoke-function",{name:b,params:a})}_OnAlert(b){alert(b.message)}_OnWrapperMessage(b){"entered-fullscreen"===b?(c._SetWrapperIsFullscreenFlag(!0),this._OnFullscreenChange()):"exited-fullscreen"===b?(c._SetWrapperIsFullscreenFlag(!1),this._OnFullscreenChange()):console.warn("Unknown wrapper message: ",
b)}})}"use strict";
self.JobSchedulerDOM=class{constructor(c){this._runtimeInterface=c;this._baseUrl=c.GetBaseURL();"preview"===c.GetExportType()?this._baseUrl+="c3/workers/":this._baseUrl+=c.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var c=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(c,this._baseUrl,{name:"DispatchWorker"});c=new MessageChannel;this._inputPort=c.port1;this._dispatchWorker.postMessage({type:"_init","in-port":c.port2},[c.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const c=this._jobWorkers.length;var d=this._runtimeInterface._GetWorkerURL("jobworker.js");d=await this._runtimeInterface.CreateWorker(d,this._baseUrl,{name:"JobWorker"+c});const g=new MessageChannel,k=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:g.port1},[g.port1]);d.postMessage({type:"init",number:c,"dispatch-port":g.port2,"output-port":k.port2},[g.port2,k.port2]);this._jobWorkers.push(d);return k.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!0,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],projectScripts:[],mainProjectScript:"",scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
{function c(d){d.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(d){super(d,"button")}CreateElement(d,g){const k=document.createElement("input");var l=k;g.isCheckbox?(k.type="checkbox",l=document.createElement("label"),l.appendChild(k),l.appendChild(document.createTextNode("")),l.style.fontFamily="sans-serif",l.style.userSelect="none",l.style.webkitUserSelect="none",l.style.display="inline-block",l.style.color="black"):k.type="button";l.style.position=
"absolute";l.addEventListener("touchstart",c);l.addEventListener("touchmove",c);l.addEventListener("touchend",c);l.addEventListener("mousedown",c);l.addEventListener("mouseup",c);l.addEventListener("keydown",c);l.addEventListener("keyup",c);k.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",d,{isChecked:k.checked}));g.id&&(k.id=g.id);this.UpdateState(l,g);return l}_GetInputElem(d){return"input"===d.tagName.toLowerCase()?d:d.firstChild}_GetFocusElement(d){return this._GetInputElem(d)}UpdateState(d,
g){const k=this._GetInputElem(d);k.checked=g.isChecked;k.disabled=!g.isEnabled;d.title=g.title;d===k?k.value=g.text:d.lastChild.textContent=g.text}})}"use strict";self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(c){super(c,"mouse");this.AddRuntimeMessageHandler("cursor",d=>this._OnChangeCursorStyle(d))}_OnChangeCursorStyle(c){document.documentElement.style.cursor=c}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(c){super(c,"touch");this.AddRuntimeMessageHandler("request-permission",d=>this._OnRequestPermission(d))}async _OnRequestPermission(c){c=c.type;let d=!0;0===c?d=await this._RequestOrientationPermission():1===c&&(d=await this._RequestMotionPermission());this.PostToRuntime("permission-result",{type:c,result:d})}async _RequestOrientationPermission(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;
try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request orientation permission: ",c),!1}}async _RequestMotionPermission(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(c){return console.warn("[Touch] Failed to request motion permission: ",c),!1}}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(c){super(c,"browser");this._exportType="";this.AddRuntimeMessageHandlers([["get-initial-state",d=>this._OnGetInitialState(d)],["ready-for-sw-messages",()=>this._OnReadyForSWMessages()],["alert",d=>this._OnAlert(d)],["close",()=>this._OnClose()],["set-focus",d=>this._OnSetFocus(d)],["vibrate",d=>this._OnVibrate(d)],["lock-orientation",d=>this._OnLockOrientation(d)],["unlock-orientation",()=>this._OnUnlockOrientation()],
["navigate",d=>this._OnNavigate(d)],["request-fullscreen",d=>this._OnRequestFullscreen(d)],["exit-fullscreen",()=>this._OnExitFullscreen()],["set-hash",d=>this._OnSetHash(d)]]);window.addEventListener("online",()=>this._OnOnlineStateChanged(!0));window.addEventListener("offline",()=>this._OnOnlineStateChanged(!1));window.addEventListener("hashchange",()=>this._OnHashChange());document.addEventListener("backbutton",()=>this._OnCordovaBackButton());"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",
d=>this._OnWin10BackRequested(d))}_OnGetInitialState(c){this._exportType=c.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}_OnReadyForSWMessages(){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(c=>
this.PostToRuntime("sw-message",c.data))}_OnOnlineStateChanged(c){this.PostToRuntime("online-state",{isOnline:c})}_OnCordovaBackButton(){this.PostToRuntime("backbutton")}_OnWin10BackRequested(c){c.handled=!0;this.PostToRuntime("backbutton")}GetNWjsWindow(){return"nwjs"===this._exportType?nw.Window.get():null}_OnAlert(c){alert(c.message)}_OnClose(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}_OnSetFocus(c){c=
c.isFocus;if("nwjs"===this._exportType){const d=this.GetNWjsWindow();c?d.focus():d.blur()}else c?window.focus():window.blur()}_OnVibrate(c){navigator.vibrate&&navigator.vibrate(c.pattern)}_OnLockOrientation(c){c=c.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(d=>console.warn("[Construct 3] Failed to lock orientation: ",d));else try{let d=!1;screen.lockOrientation?d=screen.lockOrientation(c):screen.webkitLockOrientation?d=screen.webkitLockOrientation(c):
screen.mozLockOrientation?d=screen.mozLockOrientation(c):screen.msLockOrientation&&(d=screen.msLockOrientation(c));d||console.warn("[Construct 3] Failed to lock orientation")}catch(d){console.warn("[Construct 3] Failed to lock orientation: ",d)}}_OnUnlockOrientation(){try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():
screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(c){}}_OnNavigate(c){var d=c.type;if("back"===d)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===d)window.history.forward();else if("reload"===d)location.reload();else if("url"===d){d=c.url;var g=c.target;c=c.exportType;"windows-uwp"===c&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(d)):self.cordova&&self.cordova.InAppBrowser?
self.cordova.InAppBrowser.open(d,"_system"):"preview"===c||"windows-webview2"===c?window.open(d,"_blank"):this._isScirraArcade||(2===g?window.top.location=d:1===g?window.parent.location=d:window.location=d)}else"new-window"===d&&(d=c.url,g=c.tag,"windows-uwp"===c.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(d)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(d,"_system"):window.open(d,g))}_OnRequestFullscreen(c){if("windows-webview2"===
this._exportType||"macos-wkwebview"===this._exportType)self.RuntimeInterface._SetWrapperIsFullscreenFlag(!0),this._iRuntime._SendWrapperMessage({type:"set-fullscreen",fullscreen:!0});else{const d={navigationUI:"auto"};c=c.navUI;1===c?d.navigationUI="hide":2===c&&(d.navigationUI="show");c=document.documentElement;c.requestFullscreen?c.requestFullscreen(d):c.mozRequestFullScreen?c.mozRequestFullScreen(d):c.msRequestFullscreen?c.msRequestFullscreen(d):c.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?
c.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):c.webkitRequestFullScreen())}}_OnExitFullscreen(){"windows-webview2"===this._exportType||"macos-wkwebview"===this._exportType?(self.RuntimeInterface._SetWrapperIsFullscreenFlag(!1),this._iRuntime._SendWrapperMessage({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&
document.webkitCancelFullScreen()}_OnSetHash(c){location.hash=c.hash}_OnHashChange(){this.PostToRuntime("hashchange",{location:location.toString()})}});"use strict";
{function c(g){g.stopPropagation()}function d(g){13!==g.which&&27!==g.which&&g.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(g){super(g,"text-input");this.AddDOMElementMessageHandler("scroll-to-bottom",k=>this._OnScrollToBottom(k))}CreateElement(g,k){let l;const v=k.type;"textarea"===v?(l=document.createElement("textarea"),l.style.resize="none"):(l=document.createElement("input"),l.type=v);l.style.position="absolute";l.autocomplete="off";
l.addEventListener("touchstart",c);l.addEventListener("touchmove",c);l.addEventListener("touchend",c);l.addEventListener("mousedown",c);l.addEventListener("mouseup",c);l.addEventListener("keydown",d);l.addEventListener("keyup",d);l.addEventListener("click",q=>{q.stopPropagation();this._PostToRuntimeElementMaybeSync("click",g)});l.addEventListener("dblclick",q=>{q.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",g)});l.addEventListener("input",()=>this.PostToRuntimeElement("change",
g,{text:l.value}));k.id&&(l.id=k.id);this.UpdateState(l,k);return l}UpdateState(g,k){g.value=k.text;g.placeholder=k.placeholder;g.title=k.title;g.disabled=!k.isEnabled;g.readOnly=k.isReadOnly;g.spellcheck=k.spellCheck;k=k.maxLength;0>k?g.removeAttribute("maxlength"):g.setAttribute("maxlength",k)}_OnScrollToBottom(g){g.scrollTop=g.scrollHeight}})}"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(c){super(c,"geolocation");this._watchId=-1;this.AddRuntimeMessageHandler("request-location",d=>this._OnRequestLocation(d));this.AddRuntimeMessageHandler("watch-location",d=>this._OnWatchLocation(d));this.AddRuntimeMessageHandler("stop-watching",()=>this._StopWatchingLocation())}_OnRequestLocation(c){navigator.geolocation.getCurrentPosition(d=>this._OnUpdate(d),d=>this._OnError(d),c)}_OnUpdate(c){const d=c.coords;this.PostToRuntime("update",
{timestamp:c.timestamp,coords:{latitude:d.latitude,longitude:d.longitude,altitude:d.altitude,accuracy:d.accuracy,altitudeAccuracy:d.altitudeAccuracy,heading:d.heading,speed:d.speed}})}_OnError(c){this.PostToRuntime("error",{message:c.message||"Unknown error"})}_StopWatchingLocation(){-1!==this._watchId&&(navigator.geolocation.clearWatch(this._watchId),this._watchId=-1)}_OnWatchLocation(c){this._StopWatchingLocation();this._watchId=navigator.geolocation.watchPosition(d=>this._OnUpdate(d),d=>this._OnError(d),
c)}});
